### PR TITLE
handle empty response component

### LINKED ISSUE #240: Reusing 204 / NoContent response
Hi,

First, thanks for this lib.
I found an unhandled case using the following OpenAPI:

```yaml
# dummy-openapi.yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '204':
          $ref: '#/components/responses/NoContent'   # <-----
# Descriptions of common components
components:
  responses:
    NoContent:
      description: The specified resource was not found
```

It gives the following exception
```console
% smithytranslate openapi-to-smithy --input dummy-openapi.yaml --force output
Failed to validate the Smithy model:
[ERROR] dummy_openapi#UsersGET: operation shape has an `output` relationship to an unresolved shape `dummy_openapi#ComponentsResponsesNoContent` | Target.UnresolvedShape N/A:0:0
Exception in thread "main" software.amazon.smithy.model.node.ExpectationNotMetException: Shape not found in model: dummy_openapi#ComponentsResponsesNoContent
        at software.amazon.smithy.model.Model.lambda$expectShape$1(Model.java:713)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at software.amazon.smithy.model.Model.expectShape(Model.java:713)
        at software.amazon.smithy.model.shapes.SmithyIdlModelSerializer.getInlineableShapes(SmithyIdlModelSerializer.java:197)
        at software.amazon.smithy.model.shapes.SmithyIdlModelSerializer.serialize(SmithyIdlModelSerializer.java:169)
        at software.amazon.smithy.model.shapes.SmithyIdlModelSerializer.lambda$serialize$1(SmithyIdlModelSerializer.java:145)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at software.amazon.smithy.model.shapes.SmithyIdlModelSerializer.serialize(SmithyIdlModelSerializer.java:145)
        at smithytranslate.cli.runners.openapi.ReportResult.getSmithyFiles(ReportResult.scala:57)
        at smithytranslate.cli.runners.openapi.ReportResult.apply(ReportResult.scala:99)
        at smithytranslate.cli.runners.OpenApi$.$anonfun$runOpenApi$1(OpenApi.scala:27)
        at smithytranslate.cli.runners.OpenApi$.$anonfun$runOpenApi$1$adapted(OpenApi.scala:27)
        at smithytranslate.cli.runners.OpenApi$.runOpenApi(OpenApi.scala:39)
        at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:51)
        at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:48)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at cats.data.Validated.andThen(Validated.scala:727)
        at com.monovore.decline.Parser$Accumulator$Validate.$anonfun$mapValidated$1(Parser.scala:413)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at cats.data.Validated.andThen(Validated.scala:727)
        at com.monovore.decline.Result.$anonfun$mapValidated$2(Result.scala:13)
        at cats.instances.Function0Instances$$anon$4.$anonfun$map$1(function.scala:100)
        at com.monovore.decline.Parser.evalResult(Parser.scala:30)
        at com.monovore.decline.Parser.$anonfun$consumeAll$3(Parser.scala:107)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.monovore.decline.Parser.$anonfun$consumeAll$1(Parser.scala:107)
        at scala.Option.map(Option.scala:242)
        at com.monovore.decline.Parser.consumeAll(Parser.scala:106)
        at com.monovore.decline.Parser.apply(Parser.scala:19)
        at com.monovore.decline.Command.parse(opts.scala:20)
        at smithytranslate.cli.CommandApp.main(CommandApp.scala:81)
        at smithytranslate.cli.Main.main(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```
whereas this is a valid OpenAPI schema.

2024-04-08-155123_1920x1020_scrot

204 / NoContent doesn't seems to be handled properly when reusing responses.

Here is the related OpenAPI documentation:
- https://swagger.io/docs/specification/describing-responses/#empty
- https://swagger.io/docs/specification/describing-responses/#reuse

### PR DESCRIPTION
**Pull request by lewisjkl**
Fixes issue where 204 NoContent reusable responses were not being handled correctly.

I'm not sure if there is a more robust way to solve this issue since in most cases we can't accurately know whether a response with no params is meant to be represented as an empty JSON object or as a Unit (no content). In the case of a 204 we can make the assumption though that the output is `Unit`.

Closes #240.

### CODE REVIEW

File: modules/openapi/tests/src/OperationSpec.scala [hunk 1]
```diff
@@ -19,649 +19,585 @@ final class OperationSpec extends munit.FunSuite {
...
-                   |    okay:
-                   |      content:
-                   |        application/json:
-                   |          schema:
-                   |            type: object
-                   |            properties:
-                   |              sNum:
-                   |                type: integer
-                   |""".stripMargin
+  test("operation - response reference 204") {
```
Comment (lewisjkl) [inline modules/openapi/tests/src/OperationSpec.scala:545]: Kinda confused why scalafmt went to town on this file.. but this is the new test, the rest are unchanged

File: modules/openapi/src/internals/OpenApiToIModel.scala [hunk 2]
```diff
@@ -252,6 +252,15 @@ private[openapi] class OpenApiToIModel[F[_]: Parallel: TellShape: TellError](
         val code = output.code
         code >= 200 && code < 300
     }.toList match {
+      case output :: Nil if output.code == 204 =>
```
Comment (Baccata) [inline modules/openapi/src/internals/OpenApiToIModel.scala:255]: Even though this works to solve the raised issue, it's actually not fixing the underlying bug : the fact that the status code is 204 should be inconsequential to the logic : you should be able to replace `204` with `200` in the test input and still get a successful result, even if it doesn't quite make sense from a REST perspective.

Comment (Baccata) [reply modules/openapi/src/internals/OpenApiToIModel.scala:255]: Following the code, I think the problem lies in these lines : 

https://github.com/disneystreaming/smithy-translate/blob/b7bf1ed7a3992899e731d924c39f15c7c14fc169/modules/openapi/src/internals/OpenApiToIModel.scala#L333-L337

When the fields are empty, a structure should probably still be recorded, but we should have a [post-processor](https://github.com/disneystreaming/smithy-translate/tree/main/modules/compiler-core/src/internals/postprocess) that'd turn all empty-structures that don't have hints to `Unit`

File: modules/openapi/tests/src/ModelWrapper.scala [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+import software.amazon.smithy.model.shapes.SmithyIdlModelSerializer
+import software.amazon.smithy.model.transform.ModelTransformer
+import software.amazon.smithy.model.traits.Trait
+import software.amazon.smithy.model.shapes.Shape
+import software.amazon.smithy.model.traits.BoxTrait
+import software.amazon.smithy.diff.ModelDiff
+import java.util.stream.Collectors
+
+// In order to have nice comparisons from test reports.
+class ModelWrapper(val model: Model) {
```
Comment (lewisjkl) [inline modules/openapi/tests/src/ModelWrapper.scala:32]: Bringing this over from smithy4s dynamic tests since the one we were using previously was prone to false-positive reports of differences since it relied on the smithy `Model#equals` method

File: modules/compiler-core/src/internals/postprocess/EmptyStructureToUnitTransformer.scala [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+
+  // consider empty if has no fields OR if has one field with Body hint (httpPayload)
+  private def isEmptyStructure(
+      defs: Map[DefId, Definition],
+      d: Definition
+  ): Boolean =
+    d match {
+      case s: Structure =>
+        (s.localFields.isEmpty && s.parents.isEmpty && s.hints.isEmpty) || {
+          def isHttpPayload =
```
Comment (Baccata) [inline modules/compiler-core/src/internals/postprocess/EmptyStructureToUnitTransformer.scala:63]: nitpick : could be a val ?

File: modules/compiler-core/src/internals/postprocess/EmptyStructureToUnitTransformer.scala [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+            s.localFields.length == 1 && s.localFields.head.hints
+              .contains(Hint.Body)
+          def isHttpPayloadEmpty = defs
```
Comment (Baccata) [inline modules/compiler-core/src/internals/postprocess/EmptyStructureToUnitTransformer.scala:66]: ditto

File: modules/openapi/tests/src/ModelWrapper.scala (hunk 3 above)
Comment (Baccata) [reply modules/openapi/tests/src/ModelWrapper.scala:32]: good idea

**Review by Baccata — APPROVED** [review]

File: modules/compiler-core/src/internals/postprocess/EmptyStructureToUnitTransformer.scala (hunk 5 above)
Comment (lewisjkl) [reply modules/compiler-core/src/internals/postprocess/EmptyStructureToUnitTransformer.scala]: Ah yeah the first one can be a val, the second one is basically a lazy val because I won't want to evaluate `localfields.head` unless it exists (which is checked in the first `isHttpPayload`. In any case, I rewrote to make it safe so they are both vals now
