### PR TITLE
Fix handling of date fields with examples

### LINKED ISSUE #214: Incorrect Date-Time Format in Examples
Description:
When converting an the sample OpenAPI specification to Smithy using smithy-translate, there is an issue with date-time examples.

Expected Behaviour:
example: '2017-07-21T17:32:28Z' should be parsed correctly as format: DateTime

Current Behaviour:
```bash
Exception in thread "main" scala.MatchError: 2017-07-21T17:32:28Z (of class java.time.OffsetDateTime)
        at smithytranslate.openapi.internals.GetExtensions$.anyToNode(GetExtensions.scala:52)
        at smithytranslate.openapi.internals.OpenApiToIModel.$anonfun$getExamplesHint$1(OpenApiToIModel.scala:571)
        at scala.Option.map(Option.scala:242)
        at smithytranslate.openapi.internals.OpenApiToIModel.getExamplesHint(OpenApiToIModel.scala:571)
        at smithytranslate.openapi.internals.OpenApiToIModel.unfold(OpenApiToIModel.scala:618)
        at smithytranslate.openapi.internals.OpenApiToIModel.unfoldAndAddExts$1(OpenApiToIModel.scala:357)
        at smithytranslate.openapi.internals.OpenApiToIModel.$anonfun$refoldOne$1(OpenApiToIModel.scala:359)
```

Sample YAML:
```yaml
openapi: '3.0.'
info:
  title: doc
  version: 1.0.0
paths:
  /test:
    post:
      operationId: testOperationId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectIn'
      responses:
        '200':
          description: test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectOut'
components:
  schemas:
    ObjectIn:
      type: object
      properties:
        s:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
      required:
        - s
    ObjectOut:
      type: object
      properties:
        sNum:
          type: integer
```

### PR DESCRIPTION
**Pull request by lewisjkl**
Closes #214.

### CODE REVIEW

File: modules/openapi/src/internals/GetExtensions.scala [hunk 1]
```diff
@@ -49,16 +51,21 @@ object GetExtensions {
...
+    case b: Boolean                  => Node.from(b)
+    case s: String                   => Node.from(s)
+    case i: Int                      => Node.from(i)
+    case d: Double                   => Node.from(d)
+    case s: Short                    => Node.from(s)
+    case l: Long                     => Node.from(l)
+    case f: Float                    => Node.from(f)
+    case n: Number                   => Node.from(n)
+    case d: java.time.OffsetDateTime => Node.from(d.toString())
+    case d: java.util.Date => Node.from(formatter.format(d.toInstant()))
```
Comment (daddykotex) [inline modules/openapi/src/internals/GetExtensions.scala:68]: should we add java.time.Instant ?

Comment (lewisjkl) [reply modules/openapi/src/internals/GetExtensions.scala:68]: So far I only added the ones that I knew could be surfaced, afaik openapi only supports `date` and `date-time` formats out of the box, which are both covered here

Comment (lewisjkl) [reply modules/openapi/src/internals/GetExtensions.scala:68]: So far I only added the ones that I knew could be surfaced, afaik openapi only supports `date` and `date-time` formats out of the box, which are both covered here

**Review by daddykotex — APPROVED** [review]
